import {
  Activity,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Building2,
  CalendarRange,
  ClipboardCheck,
  Cloud,
  Database,
  Eye,
  FileChartColumn,
  FileCheck2,
  FileSearch,
  FileText,
  Gauge,
  GitBranch,
  Globe,
  Layers,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Lock,
  MessageSquare,
  Network,
  NotebookPen,
  Radar,
  RefreshCw,
  ScanEye,
  ScanSearch,
  Scale,
  Server,
  ShieldCheck,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  Users,
  Waypoints,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ccmIcons: Record<string, LucideIcon> = {
  Activity,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Building2,
  CalendarRange,
  ClipboardCheck,
  Cloud,
  Database,
  Eye,
  FileChartColumn,
  FileCheck2,
  FileSearch,
  FileText,
  Gauge,
  GitBranch,
  Globe,
  Layers,
  LayoutDashboard,
  LineChart,
  ListChecks,
  Lock,
  MessageSquare,
  Network,
  NotebookPen,
  Radar,
  RefreshCw,
  ScanEye,
  ScanSearch,
  Scale,
  Server,
  ShieldCheck,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  Users,
  Waypoints,
  Workflow,
  Zap,
};

export function CcmIcon({
  name,
  size = 20,
  strokeWidth = 1.75,
  className,
}: {
  name: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  const Icon = ccmIcons[name] ?? ShieldCheck;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
